version: "3"
services:
##### DATABASES #####
  dbmysqlsemi:
    image: mysql:5.7
    restart: always
    container_name: dbmysqlsemi    
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=proyecto
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
      - mysql-semi:/var/lib/mysql  
    networks:
      - app_net
############## API ##################

  apisemi:
    container_name: apisemi
    build: ./backend
    image: apisemi:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=proyecto
      - MYSQL_PASSWORD=root
      - MYSQL_HOSTNAME=dbmysqlsemi
      - MYSQL_PORT=3306
    ports:
      - "4000:4000"
    depends_on:
      - dbmysqlsemi
    networks:
      - app_net
############## FRONTEND ##################
  frontend:
    image: 'alvarosp24/semi_frontend'
    container_name: 'semi_frontend'
    environment:
      REACT_APP_PUERTO: "localhost" #localhost
    ports:
      - '80:4200' #del no de hub al mio
    restart: always
    depends_on:
      - apisemi

volumes:
  mysql-semi:


networks:
  app_net:
    driver: bridge