-- MySQL Script generated by MySQL Workbench
-- dom 16 abr 2023 22:58:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `dpi` VARCHAR(45) NOT NULL,
  `foto` TEXT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicaciones` (
  `id` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `foto` TEXT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publicaciones_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `publicaciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentarios_publicaciones1_idx` (`publicaciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`publicaciones_id`)
    REFERENCES `mydb`.`publicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amigos` (
  `id` INT NOT NULL,
  `state` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_amigos_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_amigos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `id` INT NOT NULL,
  `name_album` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album_fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album_fotos` (
  `id` INT NOT NULL,
  `album_id` INT NOT NULL,
  `publicaciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_fotos_album1_idx` (`album_id` ASC) VISIBLE,
  INDEX `fk_album_fotos_publicaciones1_idx` (`publicaciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_fotos_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `mydb`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_fotos_publicaciones1`
    FOREIGN KEY (`publicaciones_id`)
    REFERENCES `mydb`.`publicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
